name: mimic4_outcome_transformer_ep100_kf0_bs64_hid64
model_type: dl
model: transformer
dataset: mimic4
task: outcome



batch_size: 64
hidden_dim: 64
num_layers: 2
output_dim: 1
act_layer: nn.GELU
drop: 0.0