name: mimic4_outcome_adacare_ep100_kf0_bs512_hid64
model_type: ehr
model: adacare
dataset: mimic4
task: outcome



batch_size: 64
hidden_dim: 64

kernel_size: 2
kernel_num: 64

output_dim: 1
act_layer: nn.GELU
drop: 0.0