# dataset settings
demo_dim: 2
lab_dim: 59
max_visits: 48
thresholds: [8,7,6,5.33518,5,4,3,2,1]


epochs: 100
num_folds: 0
train_fold: 0
dataset_split_seed: 42
model_init_seed: [42]
wandb: True
wandb_project: Baseline-EHR
