# dataset settings
demo_dim: 2
lab_dim: 73
max_visits: 13
thresholds: [8,7,6,5.1195875,5,4.5,4,3,2,1]
large_los: 26.0

epochs: 100
num_folds: 5
train_fold: 1
dataset_split_seed: 42
model_init_seed: [0, 31, 42, 131, 1331]
