name: hm_los_adacare_ep100_kf10_bs512_hid128
model_type: ehr
model: adacare
dataset: hm
task: los



batch_size: 512
hidden_dim: 128

kernel_size: 2
kernel_num: 64

output_dim: 1
act_layer: nn.GELU
drop: 0.0