name: hm_los_tcn_ep100_kf10_bs512_hid128
model_type: dl
model: tcn
dataset: hm
task: los
epochs: 100
num_folds: 10
train_fold: 1
batch_size: 512
hidden_dim: 128
kernel_size: 2
dropout: 0.0
output_dim: 1