name: hm_los_agent_ep100_kf10_bs512_hid64
model_type: ehr
model: agent
dataset: hm
task: los



batch_size: 512
hidden_dim: 64

cell: gru
n_actions: 10
n_units: 64
lamda: 0.5

output_dim: 1
act_layer: nn.GELU
drop: 0.0