name: hm_multitask_stagenet_ep100_kf10_bs512_hid64
model_type: dl
model: stagenet
dataset: hm
task: multitask
epochs: 100
num_folds: 10
train_fold: 1
batch_size: 512
hidden_dim: 64
conv_size: 10
levels: 4
drop: 0.5
output_dim: 1