name: hm_outcome_agent_ep100_kf10_bs512_hid64
model_type: dl
model: agent
dataset: hm
task: outcome
epochs: 100
num_folds: 10
train_fold: 1
batch_size: 512
hidden_dim: 64

cell: gru
n_actions: 10
n_units: 64
lamda: 0.5

output_dim: 1
act_layer: nn.GELU
drop: 0.0