name: hm_outcome_concare_ep100_kf10_bs512_hid128
model_type: ehr
model: concare
dataset: hm
task: outcome
epochs: 100
num_folds: 10
train_fold: 1
batch_size: 512
hidden_dim: 128

MHD_num_head: 4

output_dim: 1
drop: 0.0