name: hm_outcome_mlp_ep100_kf10_bs64_hid64
model_type: dl
model: mlp
dataset: hm
task: outcome
epochs: 100
num_folds: 10
train_fold: 1
batch_size: 64
hidden_dim: 64
output_dim: 1
act_layer: nn.GELU
drop: 0.0