name: hm_twostage_concare_kf10
model_type: ehr
model: concare
dataset: hm
task: twostage

outcome_model_name: hm_outcome_concare_ep100_kf10_bs64_hid128
los_model_name: hm_los_concare_ep100_kf10_bs64_hid64
