name: hm_twostage_transformer_kf10
model_type: dl
model: transformer
dataset: hm
task: twostage

outcome_model_name: hm_outcome_transformer_ep100_kf10_bs64_hid128
los_model_name: hm_los_transformer_ep100_kf10_bs64_hid128
