name: hm_transformer_multitask_ep100_kf10_bs64_hid128
model_type: dl
model: transformer
dataset: hm
task: multitask
epochs: 100
num_folds: 10
train_fold: 1
batch_size: 64
hidden_dim: 128
output_dim: 1
act_layer: nn.GELU
drop: 0.0