name: hm_twostage_transformer_ep100_kf10_bs512_hid64
model_type: dl
model: transformer
dataset: hm
task: twostage
epochs: 100
num_folds: 10
train_fold: 1
batch_size: 512
hidden_dim: 64
num_layers: 2
output_dim: 1
act_layer: nn.GELU
drop: 0.0