name: hm_twostage_xgboost
model_type: ml
model: xgboost
dataset: hm
task: twostage
outcome_model_name: hm_outcome_xgboost_kf10_lr0.1_md7_cw3_test
los_model_name: hm_los_xgboost_kf10_lr0.01_md5_cw3_test
