name: hm_twostage_adacare_ep100_kf10_bs512_hid128
model_type: ehr
model: adacare
dataset: hm
task: twostage
epochs: 100
num_folds: 10
train_fold: 1
batch_size: 512
hidden_dim: 128

kernel_size: 2
kernel_num: 64

output_dim: 1
act_layer: nn.GELU
drop: 0.0