name: hm_twostage_grasp_ep100_kf10_bs512_hid128
model_type: ehr
model: grasp
dataset: hm
task: twostage
epochs: 100
num_folds: 10
train_fold: 1
batch_size: 512
hidden_dim: 128

cluster_num: 24

output_dim: 1
drop: 0.0