name: hm_twostage_stagenet_kf10
model_type: ehr
model: stagenet
dataset: hm
task: twostage

outcome_model_name: hm_outcome_stagenet_ep100_kf10_bs512_hid64
los_model_name: hm_los_stagenet_ep100_kf10_bs512_hid64
