name: hm_twostage_retain_kf10
model_type: ehr
model: retain
dataset: hm
task: twostage

outcome_model_name: hm_outcome_retain_ep100_kf10_bs512_hid128
los_model_name: hm_los_retain_ep100_kf10_bs512_hid128
