name: tj_los_transformer_ep100_kf10_bs64_hid128
model_type: dl
model: transformer
dataset: tongji
task: los
epochs: 100
num_folds: 10
train_fold: 10
batch_size: 64
hidden_dim: 128
num_layers: 2
output_dim: 1
act_layer: nn.GELU
drop: 0.0