name: tj_multitask_adacare_ep100_kf10_bs64_hid64
model_type: ehr
model: adacare
dataset: tongji
task: multitask



batch_size: 64
hidden_dim: 64

kernel_size: 2
kernel_num: 64

output_dim: 1
act_layer: nn.GELU
drop: 0.0