name: tj_multitask_grasp_ep100_kf10_bs64_hid128
model_type: ehr
model: grasp
dataset: tongji
task: multitask
epochs: 100
num_folds: 10
train_fold: 10
batch_size: 64
hidden_dim: 128

cluster_num: 24

output_dim: 1
drop: 0.0