name: tj_multitask_transformer_ep100_kf10_bs64_hid128
model_type: dl
model: transformer
dataset: tongji
task: multitask



batch_size: 64
hidden_dim: 128
num_layers: 2
output_dim: 1
act_layer: nn.GELU
drop: 0.0