name: tj_multitask_agent_ep100_kf10_bs64_hid128
model_type: ehr
model: agent
dataset: tongji
task: multitask



batch_size: 64
hidden_dim: 128

cell: gru
n_actions: 10
n_units: 64
lamda: 0.5

output_dim: 1
act_layer: nn.GELU
drop: 0.0