name: tj_outcome_stagenet_ep100_kf10_bs64_hid64
model_type: ehr
model: stagenet
dataset: tongji
task: outcome
epochs: 100
num_folds: 10
train_fold: 10
batch_size: 64
hidden_dim: 64
conv_size: 10
levels: 4
drop: 0.5
output_dim: 1