name: tj_twostage_adacare_kf10
model_type: ehr
model: adacare
dataset: tongji
task: twostage

outcome_model_name: tj_outcome_adacare_ep100_kf10_bs64_hid64
los_model_name: tj_los_adacare_ep100_kf10_bs64_hid64
