name: tj_twostage_transformer_kf10
model_type: dl
model: transformer
dataset: tongji
task: twostage

outcome_model_name: tj_outcome_transformer_ep100_kf10_bs64_hid128
los_model_name: tj_los_transformer_ep100_kf10_bs64_hid128
