name: tj_twostage_retain_kf10
model_type: ehr
model: retain
dataset: tongji
task: twostage

outcome_model_name: tj_outcome_retain_ep100_kf10_bs64_hid128
los_model_name: tj_los_retain_ep100_kf10_bs64_hid128
