name: tj_twostage_concare_kf10
model_type: ehr
model: concare
dataset: tongji
task: twostage

outcome_model_name: tj_outcome_concare_ep100_kf10_bs64_hid128
los_model_name: tj_los_concare_ep100_kf10_bs64_hid64
