name: tj_twostage_agent_kf10
model_type: ehr
model: agent
dataset: tongji
task: twostage

outcome_model_name: tj_outcome_agent_ep100_kf10_bs64_hid128
los_model_name: tj_los_agent_ep100_kf10_bs64_hid64
