name: tj_twostage_grasp_kf10
model_type: ehr
model: grasp
dataset: tongji
task: twostage

outcome_model_name: tj_outcome_grasp_ep100_kf10_bs64_hid64
los_model_name: tj_los_grasp_ep100_kf10_bs64_hid64
